### ISSUE TITLE
Compile time error in ubuntu 18.04.2

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#739]
had to add `#include "agspalrender/agsplugin.h"` before `#include "plugin/agsplugin.h"` in `ags_palrender.cpp"`

Then i had to further add to `ac/scriptcontainers.cpp`, `ac/dynobj/scriptset.cpp` and `ac/dynobj/scriptdict.cpp` on top before the other includes `#include <string.h>` and in `` because `strlen` wasn't appearing.

This is probably because `note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)`

so gcc got stricter by default or something. 

Then i had this error much latter:
platform/linux/acpllnx.cpp:188:75: error: no ‘void AGSLinux::GetSystemDisplayModes(std::vector<AGS::Engine::DisplayMode>&)’ member function declared in class ‘AGSLinux’
 void AGSLinux::GetSystemDisplayModes(std::vector<Engine::DisplayMode> &dms)
           
Which I 'tried' to fix by adding the declaration on the  struct at the top.

Then i tried to compile and got a bunch of PIC errors (`can not be used when making a PIE object; recompile with -fPIC`) and the `undefined reference to vtable for AGSLinux` (the 'evolution' of the error above), and i quit trying. I noticed there is a cmake version but it also had it's problems and i couldn't end up with a working exe in the last step either after 'solving' those.

Just thought to let you know. Thanks for the engine folks.

**Comment by ivan-mogilko** [comment]
Please tell what branch are you compiling?

**Comment by i30817** [comment]
main, got with `git clone --depth=1 git://github.com/adventuregamestudio/ags.git`. I'm on 64 bits if it matters.

**Comment by i30817** [comment]
This is the final errors after those hacks:
```

make: Entering directory '/media/i30817/Huggin/Documents/projects/ags/Engine'
CFLAGS = -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Engine/libsrc/freetype-2.1.3/include -I../Engine -I../Common -I../Common/libinclude -I../Plugins -I../Engine/libsrc/glad/include 

CXXFLAGS = -std=c++11 -Werror=delete-non-virtual-dtor -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Engine/libsrc/freetype-2.1.3/include -I../Engine -I../Common -I../Common/libinclude -I../Plugins -I../Engine/libsrc/glad/include 

MMFLAGS = 

LDFLAGS = -rdynamic -Wl,--as-needed 

LIBS = -Wl,-Bdynamic -lalleg -lX11 -logg -ltheora -logg -lvorbis -lvorbisfile -ldl -lpthread -lc -lm -lstdc++ -Wl,--push-state,-Bstatic -laldmb -ldumb -Wl,--pop-state 

Linking engine...
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libaldmb.a(packfile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(rendsig.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(itrender.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(resample.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(itread.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(reads3m.o): relocation R_X86_64_32S against symbol `_dumb_sigtype_it' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(readxm.o): relocation R_X86_64_32S against symbol `_dumb_sigtype_it' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(readmod.o): relocation R_X86_64_32S against symbol `_dumb_sigtype_it' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdumb.a(xmeffect.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
platform/linux/acpllnx.o: In function `AGSPlatformDriver::GetDriver()':
/media/i30817/Huggin/Documents/projects/ags/Engine/platform/linux/acpllnx.cpp:43: undefined reference to `vtable for AGSLinux'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'ags' failed
make: *** [ags] Error 1
make: Leaving directory '/media/i30817/Huggin/Documents/projects/ags/Engine'

```

**Comment by ivan-mogilko** [comment]
Okay, this is an organizational fault which cause misleading, but the stable version is in "ags3" branch right now, and "master" is more like an experimental place at the moment.
I merged new stuff from ags3 to master recently and some errors could remain. I will try to fix these in following days.

**Comment by i30817** [comment]
Ohh. Ok then.

**Comment by ivan-mogilko** [comment]
Wait, this should not be closed, it's still a valid report.

**Comment by i30817** [comment]
BTW, the fPIC errors remain on the ags3 branch so i tried [this](https://stackoverflow.com/questions/19364969/compilation-fails-with-relocation-r-x86-64-32-against-rodata-str1-8-can-not/19365454)

Which was advice to turn on the flag on the gcc options, which i did on both CFLAGS and CXXFLAGS on Engine/Makefile-defs.linux, but it didn't actually change anything, so now [i'm wondering if it's the same problem as the second or third answer](https://stackoverflow.com/a/42388145)

**Comment by i30817** [comment]
libaldmb, which has those errors apparently has its .so as a symlink to the libaldmb.a, ie: it's probably always a .a even when you're trying to build as a .so? Weird.

check out the data.tar.gz inside this deb of the dev pkg: https://launchpad.net/ubuntu/saucy/amd64/libaldmb1-dev/1:0.9.3-6

**Comment by ivan-mogilko** [comment]
TBH I am little confused here, does it try to use libdumb from some other place? We include these libraries as sources in Engine/libsrc.

**Comment by i30817** [comment]
Ah, the build docs say to install it. Currently i'm trying to build it from source and install it, but i should try uninstalling first.

**Comment by rofl0r** [comment]
yeah you need dumb installed. compile it with -fPIC and install it into the standard library path, or add LDFLAGS="-L /path/to/libdumb.a.etc/" before you run make in the Engine dir.

**Comment by i30817** [comment]
Yeah, it was two problems: i didn't put in `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` on the cmakefile of dumb, and i was building a shared library instead of a static one from copy pasting the build cmake line from their github page.

Works now

**Comment by rofl0r** [comment]
CMake was added (single-handedly pushed without approval by someone with write access) not even 2 weeks ago, and there are already the first issues. yay ?

**Comment by ivan-mogilko** [comment]
@i30817 do you mean cmake in our repository or libdumb one?

**Comment by i30817** [comment]
The libdumb, i didn't even know that the library was in the repo, and the linux instructions said to install the distro package, so i went straight to the original to try to fix it.

**Comment by ivan-mogilko** [comment]
Hmm, I don't know about Scripts/download.sh, it seem to be used for other purposes. I usually just installed what is said in Linux/Readme.md, and then either `cd Engine , make` to build just the executable or `fakeroot debian/rules binary` to create deb package.

**Comment by i30817** [comment]
Yeah, that uh, is not working on ubuntu right now. Because of libdumb being built without PIC apparently. And the ubuntu version is 1.0 and the repo version is 2.0 (though it didn't seem to affect compilation since it went up until the linker).

**Comment by sonneveld** [comment]
If you have the opportunity, could you please install cmake 3.14 and try the AGS CMakefile ?  There are official deb packages here: https://blog.kitware.com/ubuntu-cmake-repository-now-available/

After installing cmake and using that build process, you won't need to build any dependencies as cmake will pull and build them for you (hopefully).

Instructions are in `CMAKE.md` but I'll post them here:

```
 - Install CMake 3.14 (via above site)
 - mkdir build-debug
 - cmake $WHERE_AGS_SOURCE_IS_LOCATED -DCMAKE_BUILD_TYPE=Debug
 - cmake --build . --parallel
```

You can swap out `Debug` for `Release` if you like.

**Comment by sonneveld** [comment]
> Hmm, I don't know about Scripts/download.sh, it seem to be used for other purposes. 

This is used for the buildlib scripts in OSX, iOS and Android. (although OSX doesn't need it when you use the cmake scripts now)

> The libdumb, i didn't even know that the library was in the repo, and the linux instructions said to install the distro package, so i went straight to the original to try to fix it. 

The version of libdumb that we use on Windows and OSX is the ancient v0.9.3. Didn't come with a CMakeLists.txt file until recently. It's true that we also bundle a CMakeList with our libsrc version but that was added specifically for our builds.

**Comment by i30817** [comment]
I had already downloaded the binary for of cmake 3.14. Not sure if that is enough or the reason this failed:
```

../cmake-3.14.3-Linux-x86_64/bin/cmake . -DCMAKE_BUILD_TYPE=Debug
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file linux/awe_voice.h
-- Looking for include file linux/awe_voice.h - not found
-- Looking for include file linux/input.h
-- Looking for include file linux/input.h - found
-- Looking for include files sys/types.h, linux/joystick.h
-- Looking for include files sys/types.h, linux/joystick.h - found
-- Looking for include file linux/soundcard.h
-- Looking for include file linux/soundcard.h - found
-- Looking for include file machine/soundcard.h
-- Looking for include file machine/soundcard.h - not found
-- Looking for include file soundcard.h
-- Looking for include file soundcard.h - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/io.h
-- Looking for include file sys/io.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/soundcard.h
-- Looking for include file sys/soundcard.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for getexecname
-- Looking for getexecname - not found
-- Looking for memcmp
-- Looking for memcmp - found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for mprotect
-- Looking for mprotect - found
-- Looking for sched_yield
-- Looking for sched_yield - found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strlwr
-- Looking for strlwr - not found
-- Looking for strupr
-- Looking for strupr - not found
-- Looking for sysconf
-- Looking for sysconf - found
-- Performing Test ALLEGRO_HAVE_SV_PROCFS_H
-- Performing Test ALLEGRO_HAVE_SV_PROCFS_H - Failed
-- Performing Test ALLEGRO_HAVE_PROCFS_ARGCV
-- Performing Test ALLEGRO_HAVE_PROCFS_ARGCV - Failed
-- Performing Test MAP_FAILED_DEFINED
-- Performing Test MAP_FAILED_DEFINED - Success
-- Performing Test ALLEGRO_USE_CONSTRUCTOR
-- Performing Test ALLEGRO_USE_CONSTRUCTOR - Success
-- Performing Test ALLEGRO_HAVE_POSIX_MONOTONIC_CLOCK
-- Performing Test ALLEGRO_HAVE_POSIX_MONOTONIC_CLOCK - Success
-- Checking for module 'alsa'
--   Found alsa, version 1.1.3
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.8
-- Checking for module 'jack'
--   Found jack, version 1.9.12
-- Looking for XOpenIM in X11
-- Looking for XOpenIM in X11 - found
-- Looking for XDGAQueryExtension in Xxf86dga
-- Looking for XDGAQueryExtension in Xxf86dga - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Performing Test HAVE_FSEEKO
-- Performing Test HAVE_FSEEKO - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
CMake Error at Engine/CMakeLists.txt:4 (add_library):
  Cannot find source file:

    ac/viewport.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at Engine/CMakeLists.txt:4 (add_library):
  No SOURCES given to target: engine


```

**Comment by i30817** [comment]
It failed... maybe precisely because i deleted viewport.cpp from the CMakeLists.txt. But that file really doesn't exist.
```

[ 98%] Building CXX object Common/CMakeFiles/common.dir/util/wgt2allg.cpp.o
[ 99%] Linking CXX static library libcommon.a
[ 99%] Built target common
Scanning dependencies of target ags
[ 99%] Building CXX object Engine/CMakeFiles/ags.dir/main/main.cpp.o
/media/i30817/Huggin/Documents/projects/ags/Engine/main/main.cpp:341:5: warning: "/*" within comment [-Wcomment]
     /*
      
/media/i30817/Huggin/Documents/projects/ags/Engine/main/main.cpp:346:5: warning: "/*" within comment [-Wcomment]
     /*
      
[100%] Linking CXX executable ../ags
libengine.a(game.cpp.o): In function `restore_game_head_dynamic_values(AGS::Common::Stream*, AGS::Engine::RestoredData&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/game.cpp:1114: undefined reference to `Camera::SetAt(int, int)'
libengine.a(gamestate.cpp.o): In function `GameState::GameState()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:48: undefined reference to `Viewport::LinkCamera(std::shared_ptr<Camera>)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:49: undefined reference to `Camera::LinkToViewport(std::weak_ptr<Viewport>)'
libengine.a(gamestate.cpp.o): In function `GameState::SetMainViewport(Rect const&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:76: undefined reference to `Viewport::SetRect(Rect const&)'
libengine.a(gamestate.cpp.o): In function `GameState::SetUIViewport(Rect const&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:133: undefined reference to `Viewport::SetRect(Rect const&)'
libengine.a(gamestate.cpp.o): In function `GameState::SetRoomViewport(int, Rect const&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:138: undefined reference to `Viewport::SetRect(Rect const&)'
libengine.a(gamestate.cpp.o): In function `GameState::UpdateRoomCamera(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:202: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:207: undefined reference to `Camera::IsLocked() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:211: undefined reference to `Camera::SetAt(int, int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:216: undefined reference to `Camera::SetAt(int, int)'
libengine.a(gamestate.cpp.o): In function `GameState::RoomToScreen(int, int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:222: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:222: undefined reference to `Camera::GetRect() const'
libengine.a(gamestate.cpp.o): In function `GameState::RoomToScreenX(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:227: undefined reference to `Camera::GetRect() const'
libengine.a(gamestate.cpp.o): In function `GameState::RoomToScreenY(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:232: undefined reference to `Camera::GetRect() const'
libengine.a(gamestate.cpp.o): In function `GameState::ScreenToRoomImpl(int, int, int, bool, bool)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:254: undefined reference to `Viewport::GetCamera() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:257: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:258: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:262: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:263: undefined reference to `Camera::GetRect() const'
libengine.a(gamestate.cpp.o): In function `GameState::CreateRoomViewport()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:296: undefined reference to `Viewport::SetID(int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:297: undefined reference to `Viewport::SetRect(Rect const&)'
libengine.a(gamestate.cpp.o): In function `GameState::DeleteRoomViewport(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:335: undefined reference to `Viewport::SetID(int)'
libengine.a(gamestate.cpp.o): In function `GameState::CreateRoomCamera()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:350: undefined reference to `Camera::SetID(int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:351: undefined reference to `Camera::SetAt(int, int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:352: undefined reference to `Camera::SetSize(Size const&)'
libengine.a(gamestate.cpp.o): In function `GameState::DeleteRoomCamera(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:389: undefined reference to `Camera::SetID(int)'
libengine.a(gamestate.cpp.o): In function `GameState::ReadFromSavegame(AGS::Common::Stream*, GameStateSvgVersion)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:553: undefined reference to `Camera::Lock()'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/gamestate.cpp:555: undefined reference to `Camera::Release()'
libengine.a(room.cpp.o): In function `unload_old_room()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:287: undefined reference to `Camera::Release()'
libengine.a(room.cpp.o): In function `adjust_viewport_to_room()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:427: undefined reference to `Camera::SetSize(Size const&)'
libengine.a(room.cpp.o): In function `update_all_viewcams_with_newroom()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:436: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:437: undefined reference to `Camera::SetSize(Size const&)'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:438: undefined reference to `Camera::SetAt(int, int)'
libengine.a(room.cpp.o): In function `load_new_room(int, CharacterInfo*)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/room.cpp:719: undefined reference to `Camera::SetAt(int, int)'
libengine.a(savegame.cpp.o): In function `AGS::Engine::RestoreViewportCameraLinks(AGS::Engine::RestoredData const&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame.cpp:436: undefined reference to `Viewport::LinkCamera(std::shared_ptr<Camera>)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame.cpp:437: undefined reference to `Camera::LinkToViewport(std::weak_ptr<Viewport>)'
libengine.a(savegame_components.cpp.o): In function `AGS::Engine::SavegameComponents::WriteCameraState(Camera const&, AGS::Common::Stream*)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:205: undefined reference to `Camera::IsLocked() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:207: undefined reference to `Camera::GetRect() const'
libengine.a(savegame_components.cpp.o): In function `AGS::Engine::SavegameComponents::WriteViewportState(Viewport const&, AGS::Common::Stream*)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:225: undefined reference to `Viewport::GetCamera() const'
libengine.a(savegame_components.cpp.o): In function `AGS::Engine::SavegameComponents::ReadCameraState(AGS::Engine::RestoredData&, AGS::Common::Stream*)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:278: undefined reference to `Camera::SetID(int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:281: undefined reference to `Camera::Lock()'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:283: undefined reference to `Camera::Release()'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:288: undefined reference to `Camera::SetAt(int, int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:289: undefined reference to `Camera::SetSize(Size const&)'
libengine.a(savegame_components.cpp.o): In function `AGS::Engine::SavegameComponents::ReadViewportState(AGS::Engine::RestoredData&, AGS::Common::Stream*)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:296: undefined reference to `Viewport::SetID(int)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:298: undefined reference to `Viewport::SetVisible(bool)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:304: undefined reference to `Viewport::SetRect(Rect const&)'
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:305: undefined reference to `Viewport::SetZOrder(int)'
libengine.a(savegame_components.cpp.o): In function `AGS::Engine::SavegameComponents::ReadGameState(std::shared_ptr<AGS::Common::Stream>, int, AGS::Engine::PreservedParams const&, AGS::Engine::RestoredData&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/game/savegame_components.cpp:347: undefined reference to `Camera::SetAt(int, int)'
libengine.a(engine.cpp.o): In function `engine_init_game_settings()':
/media/i30817/Huggin/Documents/projects/ags/Engine/main/engine.cpp:1017: undefined reference to `Camera::Release()'
libengine.a(engine_setup.cpp.o): In function `engine_init_resolution_settings(Size)':
/media/i30817/Huggin/Documents/projects/ags/Engine/main/engine_setup.cpp:135: undefined reference to `Camera::SetSize(Size const&)'
libengine.a(game_run.cpp.o): In function `game_loop_do_render_and_check_mouse(AGS::Engine::IDriverDependantBitmap*, int, int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/main/game_run.cpp:619: undefined reference to `Viewport::GetCamera() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/main/game_run.cpp:625: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/main/game_run.cpp:626: undefined reference to `Camera::GetRect() const'
libengine.a(draw.cpp.o): In function `sync_roomview(std::shared_ptr<Viewport>)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:581: undefined reference to `Viewport::GetCamera() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:587: undefined reference to `Camera::GetRect() const'
libengine.a(draw.cpp.o): In function `on_camera_size_changed(int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:638: undefined reference to `Camera::GetLinkedViewports() const'
libengine.a(draw.cpp.o): In function `draw_room_background(std::shared_ptr<Viewport>, AGS::Engine::SpriteTransform const&)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:2072: undefined reference to `Viewport::GetCamera() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:2073: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:2073: undefined reference to `Camera::GetRect() const'
libengine.a(draw.cpp.o): In function `construct_room_view()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:2420: undefined reference to `Viewport::GetCamera() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/draw.cpp:2424: undefined reference to `Camera::GetRect() const'
libengine.a(global_debug.cpp.o): In function `script_debug(int, int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_debug.cpp:113: undefined reference to `Camera::GetRect() const'
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_debug.cpp:174: undefined reference to `Camera::GetRect() const'
libengine.a(global_viewport.cpp.o): In function `SetViewport(int, int)':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_viewport.cpp:22: undefined reference to `Camera::LockAt(int, int)'
libengine.a(global_viewport.cpp.o): In function `ReleaseViewport()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_viewport.cpp:25: undefined reference to `Camera::Release()'
libengine.a(global_viewport.cpp.o): In function `GetViewportX()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_viewport.cpp:28: undefined reference to `Camera::GetRect() const'
libengine.a(global_viewport.cpp.o): In function `GetViewportY()':
/media/i30817/Huggin/Documents/projects/ags/Engine/ac/global_viewport.cpp:31: undefined reference to `Camera::GetRect() const'
libengine.a(exports.cpp.o): In function `setup_script_exports(ScriptAPIVersion, ScriptAPIVersion)':
/media/i30817/Huggin/Documents/projects/ags/Engine/script/exports.cpp:95: undefined reference to `RegisterViewportAPI()'
collect2: error: ld returned 1 exit status
Engine/CMakeFiles/ags.dir/build.make:113: recipe for target 'ags' failed
make[2]: *** [ags] Error 1
CMakeFiles/Makefile2:943: recipe for target 'Engine/CMakeFiles/ags.dir/all' failed
make[1]: *** [Engine/CMakeFiles/ags.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

Don't worry about it, i already have a working exec.

**Comment by ivan-mogilko** [comment]
It should be `viewport_script.cpp`

**Comment by sonneveld** [comment]
Easy fix. I've pushed the changes to `ags3`.

**Comment by i30817** [comment]
Ok, that makes sense. 

BTW you probably want to make the cmake build output the makefiles to the current dir instead of the source,  like some other projects @sonneveld . I tried it (your instructions even had a mkdir) but it always writes to the main dir and the build-debug stayed empty.

Not a big deal but something.

**Comment by sonneveld** [comment]
> BTW you probably want to make the cmake build output the makefiles to the current dir instead of the source, like some other projects @sonneveld . I tried it (your instructions even had a mkdir) but it always writes to the main dir and the build-debug stayed empty.

That's really weird. I do not see that behaviour at all. 

Oh wait, you'll need to change to `build-debug`.  Missed a step there.

**Comment by i30817** [comment]
I did change dir. Maybe it's because i'm invoking cmake with a relative path instead of having it in BIN.
```

i30817@AIVAS:/media/i30817/Huggin/Documents/projects/ags/build-debug$ ../../cmake-3.14.3-Linux-x86_64/bin/cmake . -DCMAKE_BUILD_TYPE=Debug
CMake Error: The source directory "/media/i30817/Huggin/Documents/projects/ags/build-debug" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
i30817@AIVAS:/media/i30817/Huggin/Documents/projects/ags/build-debug$ ../../cmake-3.14.3-Linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /media/i30817/Huggin/Documents/projects/ags

```
As you can see, something weird.

Anyway it fails with the same fail output in the linking step as above. Dunno why. If it doesn't happen to you, it's probably my fault.

**Comment by sonneveld** [comment]
That looks like normal behaviour. The first time you ran cmake, you using the relative directory `.` which explains why it couldn't find any files.

The second time looks like it configured correctly. If you type `make -j8` or `cmake --build . --parallel`, you should get a binary.

**Comment by sonneveld** [comment]
> one git stash; git pull later
> [100%] Built target ags
> 
> so it's working.

yay!

**Comment by i30817** [comment]
> explains why it couldn't find any files. The second time looks like it configured correctly.

Sure. But you noticed it wrote the build files to the parent dir (ie: the ags dir) and not the 'build-debug' dir right?

**Comment by sonneveld** [comment]
> Sure. But you noticed it wrote the build files to the parent dir (ie: the ags dir) and not the 'build-debug' dir right? 

I did not. Sorry about that.

> edit: to be honest this is _probably_ because i'm using a not installed cmake so the executable is being run from '../../cmake_etc' instead of the current dir. Don't worry about it.

Actually I think it's because you accidentally started off with an in source build, cmake was just re-configuring that instead of treating it like a source directory.  Confusing I know.

Recent versions of cmake now let you explicitly provide the build and source directories separately:

`cmake -S $AGS_SOURCE -B $AGS_BUILD_DEBUG`

Thanks for debugging this. You're right, it will help when clarifying the build documentation.

**Comment by ericoporto** [comment]
In my system (Ubuntu 20.04), the Makefile works if I use the in built libraries:
```
$ make USE_BUILT_IN_LIBSRC=1
```

If I let the default, (`USE_BUILT_IN_LIBSRC=0`), I get an error.

```
$ make 
CFLAGS = -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Common/libsrc/freetype-2.1.3/include -I../Engine -I../Common -I../Common/libinclude -I../Common/libsrc/alfont-2.0.9 -I../Plugins -I../Engine/libsrc/glad/include 

CXXFLAGS = -std=c++11 -Werror=delete-non-virtual-dtor -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Common/libsrc/freetype-2.1.3/include -I../Engine -I../Common -I../Common/libinclude -I../Common/libsrc/alfont-2.0.9 -I../Plugins -I../Engine/libsrc/glad/include 

MMFLAGS = 

LDFLAGS = -rdynamic -Wl,--as-needed 

LIBS = -Wl,-Bdynamic -lalleg -lX11 -logg -ltheora -logg -lvorbis -lvorbisfile -ldl -lpthread -lc -lm -lstdc++ -Wl,--push-state,-Bstatic -laldmb -ldumb -Wl,--pop-state 

Linking engine...
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(itrender.o): in function `update_effects':
(.text+0x3a58): undefined reference to `__exp_finite'
/usr/bin/ld: (.text+0x3a87): undefined reference to `__exp_finite'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(itrender.o): in function `process_tick':
(.text+0x3cf0): undefined reference to `__exp_finite'
/usr/bin/ld: (.text+0x3d34): undefined reference to `__exp_finite'
/usr/bin/ld: (.text+0x3e02): undefined reference to `__exp_finite'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(itrender.o):(.text+0x4664): more undefined references to `__exp_finite' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(itrender.o): in function `it_filter.isra.0':
(.text+0x4767): undefined reference to `__exp2_finite'
/usr/bin/ld: (.text+0x47a4): undefined reference to `__exp_finite'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(clickrem.o): in function `dumb_remove_clicks.part.0':
(.text+0x150): undefined reference to `__exp2_finite'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(readxm.o): in function `dumb_read_xm_quick':
(.text+0xa76): undefined reference to `__exp_finite'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdumb.a(readmod.o): in function `dumb_read_mod_quick':
(.text+0x3b7): undefined reference to `__exp_finite'
/usr/bin/ld: (.text+0x7bb): undefined reference to `__log_finite'
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: ags] Error 1
```
The default of the CMake works, but I don't know which is. My guess is the CMake defaults to non-system libraries.

**Comment by ivan-mogilko** [comment]
@ericoporto initially this ticket was about compilation errors in **ags4** branch, which we related to changes in plugin api, and may have been fixed since (hence I tagged it with "needs testing").
Then discussion went towards other things.

If there's a problem with cmake in current master, I propose opening another ticket to keep problems separate, because rn it's hard to tell what the ticket is about and what kind of fixing is expected.

**Comment by ericoporto** [comment]
I agree this ticket became confusing. I think @i30817 got it working eventually, so this ticket can be closed.

**Comment by i30817** [comment]
Yes, it can be closed.

**Comment by ivan-mogilko** [comment]
I will just check if ags4 compiles under ubuntu, and get back to close this then.

**Comment by ivan-mogilko** [comment]
My bad, closing now.
